### PR TITLE
Version 2.0 - Beagle

### PR DESCRIPTION
**Pull request by masseelch**
This PR tracks the progress of v4.0.0. Fixes Issue #23.

#### Religion - _**localization done**_
- [x] Moksha religious strength changed to 100% (from 50% [base game])
- [x] Itinerant preachers-belief changed to 30% (from 40% [base game])
- [x] re-ban the condemn-button
  - [x] remove old behaviour
  - [x] remove the button
- [x] Remove BBG changes to **Remove Heresy**
- [x] Worship buildings - Cost to 180 (from 120)

#### Pantheon - _**localization done**_
- [x] Religious Settlement:
  - [x] +25% production toward settlers (see GDoc raw production gain value)
  - [x] + 2 free tiles when settling.
  - [x] +50% border grow rate
- [x] Religious Idols: +3 faith +3 gold (from +2/+2)
- [x] Initiation Rites:
  - [x] Gain 40% of production cost as faith when a unit is trained.
  - [x] Get 2 free warrior when the pantheon is picked
  - [x] Healing when clear barbarian camp removed.
- [x] Divine Spark: +1 great engineer point on workshop

#### Barbs - _**no localization necessary**_
- [ ] delay barbarians galley / quadrireme. → ich glaube der einzige Punkt, den Florian nachvollziehbarerweise gerne übernommen sähe. Irgendwie so etwas wie: keine Barbarengaleeren / Barbarenquadriremen vor Zug 5 / 10 (?)

#### Policies - _**localization partially done**_
- [x] ‘Bastion’ range shot at +6 (from +10).
- [x] Fixed a bug where Jongs were receiving additional invisible production from the naval military cards
- [x] ‘Rationalism’, ‘Simultaneum’, ‘Grand Opera’ requirement: 12 pop, +4 adjacency

#### Inspirations & Heurekas _**localization done**_
- [x] Military Tactics: Build a Barracks (was kill a unit with a spearman) **[already implemented by CODENAUGH]**
- [x] Square Rigging: Build 2 Lighthouses (was kill a unit with Musketman) **[already implemented by CODENAUGH]**

#### Congress - _**localization done**_
- [x] Trade routes now provide -50% yields rather than being canceled **[already implemented by CODENAUGH]**

#### Govnerments _**localization done**_
- [x] ‘Monarchy’ gives 2 culture for each renaissance wall (instead of 2 diplomatic favor)

#### Great People - _**no localization necessary**_
- [x] Imhotep - Charges to 1 (from 2)

#### Districts _**localization done**_
- [x] Commercial Hub:
  - [x] Banks:
    - [x] Bank cost is 580g online speed
    - [x] Base yield : 6 golds (from 5)
    - [x] Great marchant point : 2 gpp (from 1)
    - [x] Trade route from cities with bank yield 2 extra golds.
    - [x] Trade route to cities with bank yield 1 extra gold.
  - [x] Stock Exchange:
    - [x] Base yield : 8 golds (from 4)
    - [x] Powered yield : 12 (from 7)
    - [x] Great marchant point : 3 gpp (from 1)
    - [x] Trade route from cities with STX yield 4 extra golds.
    - [x] Trade route to cities with STX yield 2 extra golds.
  - [x] Grand Bazar (Ottomans UB)
    - [x] Revert to base game (Bank replacement)
    - [x] Get same change as classic bank (+ base yield, gpp and traderoute buff)
    - [x] Still at reduced cost (110 insead of 145)
    - [x] Still have his unique ability (extra strategic ressources)
    - [x] Get 1 extra trader
    - [x] Get 1 governor title the first a grand bazaar is built.

#### Units - _**no localization necessary**_
- [x] Submarines now cost oil (to build / to maintain)
- [x] Infantry to 80 (from 75)
- [x] Digger to 83 (from 78) [Australia Unique Unit]
- [x] AT Crew to 80 (from 75)
- [x] Mechanized infantry to 90 (from 85)
- [x] Modern AT to 90 (from 85)
- [x] GDR Melee to 140 (from 130)
- [x] GDR Anti-Air to 120, +20 with future tech (from 100 + 30)
- [x] Courser (and Malon) production cost reduced to 90 at online speed (from 100)

#### Miscellaneous - _**no localization necessary**_
- [x] Meteor loot table changed:
  - [x] 2 Eureka, 1% chance. (So 100% before turn 15).
  - [x] Heavy chariot, 99% chance, minimum turn 15 (online speed).
- [x] Dam and Canal to 54 cost instead of 81

#### Incorporate Mods
- [x] BS https://github.com/Infixo/Civ6-Mods/tree/master/BRS
- [x] Extended Policy Cards https://steamcommunity.com/sharedfiles/filedetails/?id=2266952591
- [x] Hide Stats Evolved
- [x] Early Strategy Harvest

### CODE REVIEW

**Comment by masseelch** [comment]
> * ‘Bastion’ range shot at +6 (from +10).

@flocke159 @miesmus +6 ist doch der Wert im Base-Game, richtig? Dann muss ich da ja nichts ändern :thinking:

**Comment by masseelch** [comment]
> Grand Bazar (Ottomans UB)
> 
>     * [ ]  Revert to base game (Bank replacement)
> 
>     * [ ]  Get same change as classic bank (+ base yield, gpp and traderoute buff)
> 
>     * [ ]  Still at reduced cost (110 insead of 145)
> 
>     * [ ]  Still have his unique ability (extra strategic ressources)
> 
>     * [ ]  Get 1 extra trader
> 
>     * [ ]  Get 1 governor title the first a grand bazaar is built.

This is civ specific, isn't it? Include? Don't?

@flocke159 @miesmus

**Comment by masseelch** [comment]
> * Courser (and Malon) production cost reduced to 90 at online speed (from 100)

@flocke159 @miesmus This is confusing since in our version the Malon is not a replacement for the courser. This is only when the BBG (iElden) changes are applied to Mapuche. Therefore this is implemented already (codenaugh did it). We neet to confirm though.

**Comment by miesmus** [comment]
> > * ‘Bastion’ range shot at +6 (from +10).
> 
> @flocke159 @miesmus +6 ist doch der Wert im Base-Game, richtig? Dann muss ich da ja nichts ändern 🤔

Im Base-Game ist der Wert bei "+5" für den ranged shot. Gleichzeitig aber erhält im Base-Game die Stadt auch noch "+6" Defense Strength. Daher kommt also die Verwirrung her. Aus den +5 eine +6 zu machen bedeutet also - im Vergleich zum Grundspiel - nach wie vor einen leichten, aber ich denke vertretbaren Buff.

**Comment by miesmus** [comment]
> > Grand Bazar (Ottomans UB)
> > ```
> > - Revert to base game (Bank replacement)
> > 
> > - Get same change as classic bank (+ base yield, gpp and traderoute buff)
> > 
> > - Still at reduced cost (110 insead of 145)
> > 
> > - Still have his unique ability (extra strategic ressources)
> > 
> > - Get 1 extra trader
> > 
> > - Get 1 governor title the first a grand bazaar is built.
> > ```
> 
> This is civ specific, isn't it? Include? Don't?
> 
> @flocke159 @miesmus

Yes it is civ-specific, as these changes target the UB of the Ottomans. No, it is not civ-specific in principle since this only reflects these changes being made to non-unique building of which the Grand Bazaar is the replacement. I would therefore include these changes. Not including them would actually indirectly weaken the Grand Bazaar in comparison, as the changes being made to the bank are buffs (greater yield, more gpp, etc.)

**Comment by miesmus** [comment]
> > * Courser (and Malon) production cost reduced to 90 at online speed (from 100)
> 
> @flocke159 @miesmus This is confusing since in our version the Malon is not a replacement for the courser. This is only when the BBG (iElden) changes are applied to Mapuche. Therefore this is implemented already (codenaugh did it). We neet to confirm though.

If in our version the Malon is no longer tied to the courser, we should not implement these changes.

**Comment by miesmus** [comment]
> ‘Rationalism’, ‘Simultaneum’, ‘Grand Opera’ requirement: 12 pop, +4 adjacency
@masseelch 
You need to adjust 'Free Market' as well to 12 pop and +4 adjacency, if it's not already done in the code. That's the analogous policy for gold-income related to commercial hubs.

**Comment by masseelch** [comment]
> > ‘Rationalism’, ‘Simultaneum’, ‘Grand Opera’ requirement: 12 pop, +4 adjacency
> 
> @masseelch You need to adjust 'Free Market' as well to 12 pop and +4 adjacency, if it's not already done in the code. That's the analogous policy for gold-income related to commercial hubs.

I changed the Requirement Set and this should affect all cards using them.

**Comment by flocke159** [comment]
> * Moksha religious strength changed to 100% (from 50% [base game])

Auf welche der Beförderungen von Moksha bezieht sich dies? 'Bishop' oder 'Grand Inquisitor'?

**Review by miesmus — APPROVED** [review]
Freakin' Fantastic

**Pull request merged**
